### ISSUE TITLE
Liste des établissements vide

### ISSUE THREAD

**Issue by ThierryM** [DSMejantel/Ecole_inclusive#15]
Adieu David,
Avec la dernière version, lorsqu'on veut afficher la liste des établissements, celle-ci est vide.
Par contre, lorsqu'on veut ajouter un nouvel établissement, on voit ceux existants.
A lèu.

**Comment by DSMejantel** [comment]
Adieu,
Erreur de ma part lors de l'ajout de restriction. C'est corrigé et déposé.
A lèu

**Comment by ThierryM** [comment]
Testé : c'est OK ! Mercé plan.

Puisqu'on est sur la carte des établissement, lorsqu'on clique sur le bouton "Ajouter depuis une carte", on a un message d'erreur systématique qui n'est pas bloquant (cf capture). C'est un comportement qui n'est pas nouveau.
![Sélection_641](https://github.com/DSMejantel/Ecole_inclusive/assets/1470067/69412a28-4498-43de-981e-06282be63d87)
A lèu

**Comment by lovasoa** [comment]
On dirait un bug de SQLPage, comme celui qui a été corrigé dans la 0.21 sur la fonction hash_password. Est-ce que vous pouvez ouvrir un bug côté SQLPage pour suivre la résolution?

**Comment by ThierryM** [comment]
Ok, j'ouvre un bug sur SQLPage.

**Comment by DSMejantel** [comment]
Désolé mais je n'ai pas réagi assez vite. L'erreur venait d'une variable qui passait mal d'une page à l'autre. J'avais voulu proposé deux boutons côte à côte dans le formulaire : un pour envoyer les valeurs, l'autre pour aller sur la page de recherche géographique.
J'ai revu complètement la présentation et le fonctionnement de ces pages.

**Comment by lovasoa** [comment]
sqlpage.fetch(null) devrait valoir null (et non retourner une erreur). Non ?

**Comment by DSMejantel** [comment]
Je viens de retester avec la version corrigée (etab_ajout.sql et etab_ajout_carte.sql sur le dépôt), cela fonctionne même si on lance une recherche sans avoir rentrer de valeur. La carte est centrée par défaut sur une zone rurale au sud de Paris. (encore un coup de Simon de Montfort)

**Comment by DSMejantel** [comment]
C'est corrigé.
D'ailleurs, il faudra que je mette à jour les sous-menus suite aux différents ajouts de fonctionnalités

**Comment by ThierryM** [comment]
Je confirme la correction du bug. Mercé plan !
