### ISSUE TITLE
erreur sql sur la page aesh_suivi.sql

### ISSUE THREAD

**Issue by lovasoa** [DSMejantel/Ecole_inclusive#3]
Je vois une erreur lorsque je me connecte en tant qu'AESH sur la page aesh_suivi.sql: https://lv4cq4l44sce5attr3puax45rm0yiebw.lambda-url.eu-west-3.on.aws/aesh_suivi.sql?id=2&tab=Profils

![image](https://github.com/DSMejantel/Ecole_inclusive/assets/552629/110fa133-681f-46c0-9034-b936e0de90f5)

```
Failed to execute SQL statement:
SELECT edt_url AS top_image, 'mis en ligne, le ' || strftime('%d/%m/%Y à %Hh%M', created_at) AS description FROM edt WHERE aesh_id = CAST(? AS TEXT) AND CAST(? AS TEXT) = 'EDT'

error returned from database: (code: 1) no such table: edt

(code: 1) no such table: edt
```

**Comment by DSMejantel** [comment]
Merci de ce signalement,
C'est corrigé dans 000_base.sql
