### ISSUE TITLE
la description du format de mot de passe requis semble incorrecte

### ISSUE THREAD

**Issue by lovasoa** [DSMejantel/Ecole_inclusive#5]
Le message dit 

> Le mot de passe doit comporter au moins 8 caractères : au moins une lettre, au moins un chiffre et un caractère spécial parmi $ @ % * + - _ ! 

Mais il semblerait que la règle implémentée soit plutôt :

Le mot de passe doit comporter au moins 8 caractères : au moins une lettre **minuscule, au moins une lettre majuscule**, au moins un chiffre et un caractère spécial parmi $ @ % * + - _ !

**Comment by DSMejantel** [comment]
Correction apportée ;
   SELECT 'Nouveau mot de passe' AS label, 'password' AS name, 'password' AS type, '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*+-_!?&])[A-Za-z\d@$!%*+-_!?&]{8,}$' AS pattern, 'Le mot de passe doit comporter au moins 8 caractères : au moins une lettre minuscule, au moins une lettre majuscule, au moins un chiffre et un caractère spécial parmi $ @ % * + - _ ! ? & ' AS description;

**Comment by DSMejantel** [comment]
Commentaire et paramètre corrigés dans 4 fichiers. Merci !
