### ISSUE TITLE
sqlpage.db

### ISSUE THREAD

**Issue by vks2** [DSMejantel/Ecole_inclusive#6]
super projet ! et comme il est facile à installer. La seule chose est, pourriez-vous soit joindre   la base de données, soit configurer les migrations.  sans données, seule une petite partie des fonctionnalités du site est disponible. vous pouvez masquer les données ou utiliser la fonction de données fictives de DBeaver (https://github.com/dbeaver/dbeaver/wiki/Mock-Data-Generation-in-DBeaver). en tout cas merci !

**Comment by lovasoa** [comment]
Je me permets de partager ici les valeurs de test que @DSMejantel m'avait partagées pour la création de l'instance de démo sur https://lv4cq4l44sce5attr3puax45rm0yiebw.lambda-url.eu-west-3.on.aws/

```sql
-- Creates an initial values for test
INSERT INTO aesh (username, aesh_name, aesh_firstname, tel_aesh, courriel_aesh)
VALUES ('marc.durand', 'DURAND', 'Marc', '04.05.06.07.08','marc.durand@ac-libre.fr');

INSERT INTO user_info (username, password_hash, nom, prenom, groupe, connexion)
VALUES ('marc.durand', '$argon2id$v=19$m=19456,t=2,p=1$9i+xJR5+dBIUSjQxdkcSOQ$R7uIW8dT+SlHoZrq9Xacnzy8GSi5pAEqzSofT0/5zCw', 'DURAND', 'Marc',1,'2024-03-04 11:49:14');

INSERT INTO user_info (username, password_hash, nom, prenom, groupe, connexion)
VALUES ('jean.dupont', '$argon2id$v=19$m=19456,t=2,p=1$JBb/dhX+7K2zAzcwsTJ5mA$1MR2kt27toJ5IUA1uLZrniIQAhTdYKJnJX/+NRnzyvE', 'DUPONT', 'Jean',2,'2024-03-04 11:49:14');

INSERT INTO etab (type, nom_etab, Lon, Lat)
VALUES ('collège', 'Bourrillon', 3.50626824362502, 44.5204430879396);

INSERT INTO eleve(nom, prenom, naissance, etab_id, classe)
VALUES ('MARTIN', 'Kevin', '2009-01-11', 1, '6eme2');

INSERT INTO referent (username, nom_ens_ref, prenom_ens_ref, tel_ens_ref, email)
VALUES ('anne.dubois','DUBOIS', 'Anne', '04.05.06.07.09','anne.dubois@ac-libre.fr');

INSERT INTO modalite (type)
VALUES ('AESH-mut');

INSERT INTO dispositif (dispo)
VALUES ('PIAL');
```

@DSMejantel , peut-être que l'on devrait inclure sur le README quelques lignes qui expliquent comment lancer une nouvelle instance de l'application et la peupler de données ?

**Comment by vks2** [comment]
Merci! ce sont des données d'authentification. peut - être quelque chose d'autre à regarder toutes les fonctionnalités du site?
en ce qui concerne les instructions - il serait bon d'ajouter les choses les plus complexes qui ont été implémentées avec sql pages avec des références au résultat final et au code source.  je suppose que c'est l'authentification, le téléchargement de documents, autre chose? merci pour ce merveilleux projet!

**Comment by DSMejantel** [comment]
Bonjour,
Merci pour vos remarques et encouragements.
Je viens de mettre à jour une nouvelle version avec plusieurs nouvelles fonctionnalités.
Le dépôt intègre les valeurs test dans le dossier /sqlpage/migrations/004_test_values.sql
Voici l'ébauche d'un pas à pas :
- 1ère étape : dans l'espace paramètres (accessible depuis le menu paramétrage)
- renseigner les différentes rubriques : dispositifs, type de notification, un établissement et des élèves, éventuellement des AESH et des référents de la MDPH
- 2nd étape :
- Dans la liste des élèves, cliquer sur l'icone "cartable" ou "triangle d'alerte" pour accéder à leur fiche et les compléter

Les dernières évolutions permettent :
- la mise en ligne de fiches-outils (en pdf de préférence) grâce au [sqlpage.persist_uploaded_file](https://sql.ophir.dev/functions.sql?function=persist_uploaded_file#function)
- une gestion des droits plus fine pour les professeurs principaux d'une classe (en modification) mais en laissant la priorité aux coordonnateurs pour les élèves relevant des dispositifs (cela se coche dans le paramétrages des dispositifs).
- une sortie prête à imprimer pour avoir un récapitulatif de chaque classe

**Comment by DSMejantel** [comment]
Bonjour,
La page du Tableau de Bord / Paramètres a été remaniée afin d'être plus claire et de voir les différentes étapes du travail de paramétrage.
Dans les dernières évolutions notables : 
- historique pluri-annuel
- importation ou mise à jour des utilisateurs 
- possibilité d'indiquer un serveur CAS pour une authentification depuis un ENT
![parametres](https://github.com/DSMejantel/Ecole_inclusive/assets/149260856/5715be68-d406-4b1a-a55d-f404d5a276d4)
![parametres_comptes](https://github.com/DSMejantel/Ecole_inclusive/assets/149260856/ec8fea1e-dcaa-44a6-a307-ed4aebc76b1f)
