### ISSUE TITLE
Impossible de créer un nouveau compte

### ISSUE THREAD

**Issue by ThierryM** [DSMejantel/Ecole_inclusive#8]
Bonjour,
À partir de la page ../parametres.sql?tab=Comptes, je n'arrive pas à créer de nouveau compte. J'obtiens ce message d'erreur concernant le mot de passe :
![Sélection_638](https://github.com/DSMejantel/Ecole_inclusive/assets/1470067/018bf257-f148-4b6d-b2b1-1fcab0651e89).
Est-ce un bug ou le problème se situe plutôt entre la chaise et l'écran  ;-) ?
J'utilise la dernière version de SQLPage v0.20.4 et les données de École Inclusive du vendredi 3/05.
Merci.
Cordialement,

Thierry

**Comment by DSMejantel** [comment]
Bonjour,
Le problème est bien entre ma chaise et mon ordi.
Je suis en train de revoir ces fichiers de paramètres d'import des comptes.
Ils fonctionnent bien chez moi à ceci près c'est que j'ai enlevé le paramètre non null au champ "password_hash".
Il n'est plus créé lors de la création de compte. On propose soit une clé d'activation soit une authentification via CAS.

Attention en cas de mise à jour, je suis en train de retravailler sur la table niveau pour supprimer le champ id. Cela simplifiera la mise à jour annuelle des comptes. Cela pourrait perturber tes affichages notification.sql. Le champ niv a la contrainte valeur unique + clé primaire et j'ai supprimé le champ id.

**Comment by ThierryM** [comment]
Merci David !
Pas de souci pour ma base : je teste pour l'instant donc pas de gravité. Je retélécharge de zéro au fur et à mesure de tes retours/correction.
Par contre, lors de la création de comptes utilisateur⋅rices comme tous les champs ne sont pas obligatoires, ça pourrait être intéressant d'indiquer ceux qui le sont (avec une astérisque par exemple).

**Comment by DSMejantel** [comment]
Ce 7 mai 2024, je viens de mettre en ligne une mise à jour permettant les importations de manière plus sûre. Simplification avec choix 'Aucun' pour les référents et l'établissement, cela a nécessité de supprimer des références/clés étrangères. La vue 'stat01' n'est plus nécessaire et a été supprimée. Attention, la table 'niveaux' a changé. Le plus simple est de relancer les migrations et ensuite d'importer l'ancienne base (corrigée) dans la nouvelle.

**Comment by ThierryM** [comment]
Mercé plan David !
Je reteste cet après-midi et ne manquerai pas de faire des remontées en cas de souci ;-).
A lèu.

**Comment by ThierryM** [comment]
Problème réglé : création de compte possible.
Mais si je modifie un compte qui n'a pas d'établissement rattaché, même si j'indique un établissement, l'enregistrement ne le prend pas en compte : on reste sur les valeurs initiales.

**Comment by DSMejantel** [comment]
Bonjour,
Merci pour tous ces tests grandeur nature !
Petite erreur d'écriture dans la modification de ce matin.
Le fichier 'compte_edit.sql' a été corrigé.
Merci pour ta vigilance

**Comment by ThierryM** [comment]
Merci à toi surtout !
Tester ne coûte pas grand chose. OK pour la prise en compte de l'établissement : ça marche maintenant.
Tu peux clôturer ce ticket.
A lèu.
