### ISSUE TITLE
Erreur "unrecognized token: " avec SQLPage v0.20.5

### ISSUE THREAD

**Issue by ThierryM** [DSMejantel/Ecole_inclusive#9]
Adieu David,
En passant sur la dernière version de SQLPage 0.20.5, je constate de multiples messages d'erreurs (cf capture).
![Sélection_639](https://github.com/DSMejantel/Ecole_inclusive/assets/1470067/aca33f62-e572-4d26-b72b-570b57948240)
A lèu,

Thierry

**Comment by lovasoa** [comment]
Bonjour ! Le problème est dans sqlpage. La syntaxe `::INT` n'existe pas dans SQLite (seulement dans PostgreSQL). Avant la 0.20.5, sqlpage transformait automatiquement `xxx::int` en `CAST(xxx AS INT)` (qui fonctionne partout).

Je vais  rétablir l'ancien fonctionnement dans la prochaine version.

**Comment by ThierryM** [comment]
Merci Ophir !

**Comment by DSMejantel** [comment]
Ce problème est résolu avec la version 0.21 de SQLpage.
Les fichiers incriminés dans École Inclusive ont été corrigés pour être dans le standard de sqlite

**Comment by DSMejantel** [comment]
Ce problème est résolu avec la version 0.21 de SQLpage.
Les fichiers incriminés dans École Inclusive ont été corrigés pour être dans le standard de sqlite
